export const CREATE_GIF_REQUEST = "CREATE_GIF_REQUEST";
export const CREATE_GIF_SUCCESS = "CREATE_GIF_SUCCESS";
export const CREATE_GIF_ERROR = "CREATE_GIF_ERROR ";

export const UPDATE_GIF_REQUEST = "UPDATE_GIF_REQUEST";
export const UPDATE_GIF_SUCCESS = "UPDATE_GIF_SUCCESS";
export const UPDATE_GIF_ERROR = "UPDATE_GIF_ERROR ";

export const DELETE_GIF_REQUEST = "DELETE_GIF_REQUEST";
export const DELETE_GIF_SUCCESS = "DELETE_GIF_SUCCESS";
export const DELETE_GIF_ERROR = "DELETE_GIF_ERROR ";

export const GET_GIF_REQUEST = "GET_GIF_REQUEST";
export const GET_GIF_SUCCESS = "GET_GIF_SUCCESS";
export const GET_GIF_ERROR = "GET_GIF_ERROR ";